[package]
name = "gexplorer"
version = "0.1.0"
edition = "2021"

[dependencies]
adw = { version = "*", package = "libadwaita", features = ["v1_5"] }
gtk = { version = "*", package = "gtk4", features = ["v4_14"] }
relm4 = { version = "*" }

[build-dependencies]
glib-build-tools = "*"
